version: '3'
services:
  bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    env_file:
      - .env
